
#define ULOOP_EVENT_QUEUE_SIZE    32
#define ULOOP_DATA_QUEUE_SIZE     1024
#define ULOOP_LISTENER_TIME_LIMIT 1000
#define ULOOP_METADATA_NAME_SIZE  4

#define ULOOP_LISTENER_COUNT      1
#define ULOOP_LISTENER_TABLE_SIZE 2
#define ULOOP_EVENT_COUNT         256
#define ULOOP_STATISTICS_ENABLED