#define ULOOP_METADATA_NAME_SIZE  4
#define ULOOP_LISTENER_COUNT      1
#define ULOOP_LISTENER_TABLE_SIZE 1
#define ULOOP_EVENT_COUNT         1
#define ULOOP_DATA_QUEUE_SIZE     1

#define E_ULOOP_TIMER_UPDATE 0
